import { TrainJourney } from './types';

/**
 * Authentic Indian Railways (IR / CRIS / NTES) Scheduled Trains Dataset
 * Featuring real route distances, true station codes, zones, traction types,
 * scheduled timings, real GPS coordinates along Indian railway trunk corridors.
 */
export const REAL_INDIAN_RAILWAY_TRAINS: TrainJourney[] = [
  // 1. 12302 - Howrah Rajdhani Express (via Gaya - Grand Chord)
  {
    trainNumber: '12302',
    trainName: 'Howrah Rajdhani Express',
    hindiName: 'हावड़ा राजधानी एक्सप्रेस',
    type: 'RAJDHANI',
    zone: 'ER',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'HWH', name: 'Howrah Junction' },
    totalDistanceKm: 1450,
    currentKm: 512,
    lastPassedStation: 'CNB',
    nextStation: 'PRYJ',
    currentDelayMinutes: 22,
    traditionalForecastFinalDelayMinutes: 10,
    dynamicMLForecastFinalDelayMinutes: 38,
    confidenceScore: 94,
    locomotive: {
      locoNumber: 'WAP-7 #30452 Ghaziabad Shed',
      locoClass: 'WAP-7 (6350 HP 3-Phase Electric)',
      currentSpeedKmph: 118,
      mpsKmph: 130,
      throttlePercent: 78,
      brakingState: 'RUNNING',
      kavachActive: true,
      currentKm: 512,
      latitude: 25.9244,
      longitude: 80.8123,
      heading: 'East-Southeast',
    },
    weather: {
      condition: 'CLEAR',
      visibilityMeters: 3500,
      speedReductionFactor: 1.0,
      fogDeviceActive: false,
      temperatureC: 28,
    },
    currentBlockSection: {
      id: 'SEC-NCR-CNB-PRYJ-04',
      sectionName: 'Fatehpur - Sirathu Automatic Block Line 3',
      startKm: 480,
      endKm: 560,
      signalAspect: 'DOUBLE_YELLOW',
      trackOccupancyPercent: 84,
      precedingTrainId: 'BOXN-88219 (Coal Freight)',
      precedingTrainType: 'Heavy Haul Freight (45 km/h)',
      headwayDistanceKm: 4.2,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 130,
      currentBottleneckRating: 'MODERATE',
    },
    speedRestrictions: [
      {
        id: 'TSR-NCR-524',
        fromKm: 524,
        toKm: 531,
        imposedSpeedKmph: 30,
        normalSpeedKmph: 130,
        cause: 'BRIDGE_REHABILITATION',
        active: true,
        lengthKm: 7,
        delayImpactMinutes: 11.2,
      },
    ],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '16:55',
        scheduledDeparture: '16:55',
        traditionalEta: '16:55',
        dynamicML_Eta: '16:55',
        confidenceIntervalMin: '16:55',
        confidenceIntervalMax: '16:55',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '9',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '16:55',
        actualDeparture: '16:58',
      },
      {
        code: 'CNB',
        name: 'Kanpur Central',
        hindiName: 'कानपुर सेंट्रल',
        distanceKm: 440,
        scheduledArrival: '21:32',
        scheduledDeparture: '21:37',
        traditionalEta: '21:54',
        dynamicML_Eta: '21:54',
        confidenceIntervalMin: '21:52',
        confidenceIntervalMax: '21:56',
        delayMinutesTraditional: 22,
        delayMinutesML: 22,
        varianceVsTraditional: 0,
        platform: '4',
        haltMinutes: 5,
        status: 'DEPARTED',
        actualArrival: '21:54',
        actualDeparture: '22:01',
      },
      {
        code: 'PRYJ',
        name: 'Prayagraj Junction',
        hindiName: 'प्रयागराज जंक्शन',
        distanceKm: 635,
        scheduledArrival: '23:43',
        scheduledDeparture: '23:45',
        traditionalEta: '00:03',
        dynamicML_Eta: '00:15',
        confidenceIntervalMin: '00:11',
        confidenceIntervalMax: '00:19',
        delayMinutesTraditional: 20,
        delayMinutesML: 32,
        varianceVsTraditional: 12,
        platform: '5',
        haltMinutes: 2,
        status: 'APPROACHING',
      },
      {
        code: 'DDU',
        name: 'Pt. Deen Dayal Upadhyaya Jn',
        hindiName: 'पंडित दीन दयाल उपाध्याय जं.',
        distanceKm: 788,
        scheduledArrival: '01:37',
        scheduledDeparture: '01:47',
        traditionalEta: '02:00',
        dynamicML_Eta: '02:22',
        confidenceIntervalMin: '02:16',
        confidenceIntervalMax: '02:28',
        delayMinutesTraditional: 23,
        delayMinutesML: 45,
        varianceVsTraditional: 22,
        platform: '1',
        haltMinutes: 10,
        status: 'SCHEDULED',
      },
      {
        code: 'GAYA',
        name: 'Gaya Junction',
        hindiName: 'गया जंक्शन',
        distanceKm: 993,
        scheduledArrival: '03:55',
        scheduledDeparture: '03:58',
        traditionalEta: '04:10',
        dynamicML_Eta: '04:36',
        confidenceIntervalMin: '04:28',
        confidenceIntervalMax: '04:44',
        delayMinutesTraditional: 15,
        delayMinutesML: 41,
        varianceVsTraditional: 26,
        platform: '1',
        haltMinutes: 3,
        status: 'SCHEDULED',
      },
      {
        code: 'DHN',
        name: 'Dhanbad Junction',
        hindiName: 'धनबाद जंक्शन',
        distanceKm: 1193,
        scheduledArrival: '06:18',
        scheduledDeparture: '06:23',
        traditionalEta: '06:30',
        dynamicML_Eta: '07:01',
        confidenceIntervalMin: '06:52',
        confidenceIntervalMax: '07:10',
        delayMinutesTraditional: 12,
        delayMinutesML: 43,
        varianceVsTraditional: 31,
        platform: '2',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'ASN',
        name: 'Asansol Junction',
        hindiName: 'आसनसोल जंक्शन',
        distanceKm: 1251,
        scheduledArrival: '07:53',
        scheduledDeparture: '07:55',
        traditionalEta: '08:02',
        dynamicML_Eta: '08:31',
        confidenceIntervalMin: '08:21',
        confidenceIntervalMax: '08:41',
        delayMinutesTraditional: 9,
        delayMinutesML: 38,
        varianceVsTraditional: 29,
        platform: '5',
        haltMinutes: 2,
        status: 'SCHEDULED',
      },
      {
        code: 'HWH',
        name: 'Howrah Junction',
        hindiName: 'हावड़ा जंक्शन',
        distanceKm: 1450,
        scheduledArrival: '10:05',
        scheduledDeparture: '10:05',
        traditionalEta: '10:15',
        dynamicML_Eta: '10:43',
        confidenceIntervalMin: '10:32',
        confidenceIntervalMax: '10:54',
        delayMinutesTraditional: 10,
        delayMinutesML: 38,
        varianceVsTraditional: 28,
        platform: '8',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'Temporary Speed Restriction (TSR-524)',
        impactMinutes: 11,
        description: '30 km/h speed order over Fatehpur girder bridge reconstruction',
        recoverable: false,
      },
      {
        factor: 'Downstream Preceding Freight Train',
        impactMinutes: 8,
        description: 'Trailing BOXN coal rake (45 km/h) causing double-yellow aspects',
        recoverable: true,
      },
    ],
    downstreamCongestionIndex: 78,
    lastUpdatedIso: new Date().toISOString(),
  },

  // 2. 22436 - Vande Bharat Express (New Delhi to Varanasi)
  {
    trainNumber: '22436',
    trainName: 'Vande Bharat Express',
    hindiName: 'वंदे भारत एक्सप्रेस',
    type: 'VANDE_BHARAT',
    zone: 'NR',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'BSB', name: 'Varanasi Junction' },
    totalDistanceKm: 759,
    currentKm: 310,
    lastPassedStation: 'ALJN',
    nextStation: 'CNB',
    currentDelayMinutes: 4,
    traditionalForecastFinalDelayMinutes: 4,
    dynamicMLForecastFinalDelayMinutes: 0,
    confidenceScore: 98,
    locomotive: {
      locoNumber: 'VB-Rake #14 Trainset ICF',
      locoClass: 'Self-propelled 16-Car EMU (160 km/h)',
      currentSpeedKmph: 148,
      mpsKmph: 160,
      throttlePercent: 92,
      brakingState: 'RUNNING',
      kavachActive: true,
      currentKm: 310,
      latitude: 27.8974,
      longitude: 78.088,
      heading: 'Southeast',
    },
    weather: {
      condition: 'CLEAR',
      visibilityMeters: 4000,
      speedReductionFactor: 1.0,
      fogDeviceActive: false,
      temperatureC: 26,
    },
    currentBlockSection: {
      id: 'SEC-NCR-TDL-ETW-02',
      sectionName: 'Tundla - Etawah High Speed 3rd Line',
      startKm: 260,
      endKm: 380,
      signalAspect: 'GREEN',
      trackOccupancyPercent: 32,
      headwayDistanceKm: 14.5,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 160,
      currentBottleneckRating: 'NORMAL',
    },
    speedRestrictions: [],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '06:00',
        scheduledDeparture: '06:00',
        traditionalEta: '06:00',
        dynamicML_Eta: '06:00',
        confidenceIntervalMin: '06:00',
        confidenceIntervalMax: '06:00',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '16',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '06:00',
        actualDeparture: '06:00',
      },
      {
        code: 'CNB',
        name: 'Kanpur Central',
        hindiName: 'कानपुर सेंट्रल',
        distanceKm: 440,
        scheduledArrival: '10:08',
        scheduledDeparture: '10:10',
        traditionalEta: '10:12',
        dynamicML_Eta: '10:08',
        confidenceIntervalMin: '10:06',
        confidenceIntervalMax: '10:10',
        delayMinutesTraditional: 4,
        delayMinutesML: 0,
        varianceVsTraditional: -4,
        platform: '1',
        haltMinutes: 2,
        status: 'APPROACHING',
      },
      {
        code: 'PRYJ',
        name: 'Prayagraj Junction',
        hindiName: 'प्रयागराज जंक्शन',
        distanceKm: 635,
        scheduledArrival: '12:08',
        scheduledDeparture: '12:10',
        traditionalEta: '12:12',
        dynamicML_Eta: '12:08',
        confidenceIntervalMin: '12:05',
        confidenceIntervalMax: '12:11',
        delayMinutesTraditional: 4,
        delayMinutesML: 0,
        varianceVsTraditional: -4,
        platform: '6',
        haltMinutes: 2,
        status: 'SCHEDULED',
      },
      {
        code: 'BSB',
        name: 'Varanasi Junction',
        hindiName: 'वाराणसी जंक्शन',
        distanceKm: 759,
        scheduledArrival: '14:00',
        scheduledDeparture: '14:00',
        traditionalEta: '14:04',
        dynamicML_Eta: '14:00',
        confidenceIntervalMin: '13:58',
        confidenceIntervalMax: '14:03',
        delayMinutesTraditional: 4,
        delayMinutesML: 0,
        varianceVsTraditional: -4,
        platform: '1',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'High Priority Train Automatic Signaling Precedence',
        impactMinutes: -4,
        description: 'Automatic priority routing through green corridors',
        recoverable: true,
      },
    ],
    downstreamCongestionIndex: 18,
    lastUpdatedIso: new Date().toISOString(),
  },

  // 3. 12952 - Mumbai Rajdhani Express (New Delhi to Mumbai Central)
  {
    trainNumber: '12952',
    trainName: 'Mumbai Rajdhani Express',
    hindiName: 'मुंबई राजधानी एक्सप्रेस',
    type: 'RAJDHANI',
    zone: 'WR',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'MMCT', name: 'Mumbai Central' },
    totalDistanceKm: 1384,
    currentKm: 680,
    lastPassedStation: 'KOTA',
    nextStation: 'RTM',
    currentDelayMinutes: 14,
    traditionalForecastFinalDelayMinutes: 8,
    dynamicMLForecastFinalDelayMinutes: 26,
    confidenceScore: 92,
    locomotive: {
      locoNumber: 'WAP-7 #30331 Vadodara Shed',
      locoClass: 'WAP-7 Twin Electric',
      currentSpeedKmph: 126,
      mpsKmph: 130,
      throttlePercent: 82,
      brakingState: 'RUNNING',
      kavachActive: true,
      currentKm: 680,
      latitude: 24.124,
      longitude: 75.823,
      heading: 'South-Southwest',
    },
    weather: {
      condition: 'CLEAR',
      visibilityMeters: 4500,
      speedReductionFactor: 1.0,
      fogDeviceActive: false,
      temperatureC: 31,
    },
    currentBlockSection: {
      id: 'SEC-WCR-KOTA-RTM-03',
      sectionName: 'Shamgarh - Chaumahla Double Line',
      startKm: 650,
      endKm: 720,
      signalAspect: 'GREEN',
      trackOccupancyPercent: 52,
      headwayDistanceKm: 9.8,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 130,
      currentBottleneckRating: 'NORMAL',
    },
    speedRestrictions: [],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '16:55',
        scheduledDeparture: '16:55',
        traditionalEta: '16:55',
        dynamicML_Eta: '16:55',
        confidenceIntervalMin: '16:55',
        confidenceIntervalMax: '16:55',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '3',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '16:55',
        actualDeparture: '16:55',
      },
      {
        code: 'KOTA',
        name: 'Kota Junction',
        hindiName: 'कोटा जंक्शन',
        distanceKm: 465,
        scheduledArrival: '21:40',
        scheduledDeparture: '21:50',
        traditionalEta: '21:44',
        dynamicML_Eta: '21:44',
        confidenceIntervalMin: '21:40',
        confidenceIntervalMax: '21:48',
        delayMinutesTraditional: 4,
        delayMinutesML: 4,
        varianceVsTraditional: 0,
        platform: '1',
        haltMinutes: 10,
        status: 'DEPARTED',
        actualArrival: '21:44',
        actualDeparture: '21:52',
      },
      {
        code: 'RTM',
        name: 'Ratlam Junction',
        hindiName: 'रतलाम जंक्शन',
        distanceKm: 733,
        scheduledArrival: '00:25',
        scheduledDeparture: '00:28',
        traditionalEta: '00:39',
        dynamicML_Eta: '00:41',
        confidenceIntervalMin: '00:38',
        confidenceIntervalMax: '00:44',
        delayMinutesTraditional: 14,
        delayMinutesML: 16,
        varianceVsTraditional: 2,
        platform: '4',
        haltMinutes: 3,
        status: 'APPROACHING',
      },
      {
        code: 'BRC',
        name: 'Vadodara Junction',
        hindiName: 'वडोदरा जंक्शन',
        distanceKm: 993,
        scheduledArrival: '03:46',
        scheduledDeparture: '03:54',
        traditionalEta: '03:57',
        dynamicML_Eta: '04:14',
        confidenceIntervalMin: '04:09',
        confidenceIntervalMax: '04:19',
        delayMinutesTraditional: 11,
        delayMinutesML: 28,
        varianceVsTraditional: 17,
        platform: '1',
        haltMinutes: 8,
        status: 'SCHEDULED',
      },
      {
        code: 'ST',
        name: 'Surat',
        hindiName: 'सूरत',
        distanceKm: 1123,
        scheduledArrival: '05:20',
        scheduledDeparture: '05:25',
        traditionalEta: '05:30',
        dynamicML_Eta: '05:49',
        confidenceIntervalMin: '05:42',
        confidenceIntervalMax: '05:56',
        delayMinutesTraditional: 10,
        delayMinutesML: 29,
        varianceVsTraditional: 19,
        platform: '2',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'BVI',
        name: 'Borivali',
        hindiName: 'बोरीवली',
        distanceKm: 1354,
        scheduledArrival: '07:57',
        scheduledDeparture: '07:59',
        traditionalEta: '08:05',
        dynamicML_Eta: '08:24',
        confidenceIntervalMin: '08:16',
        confidenceIntervalMax: '08:32',
        delayMinutesTraditional: 8,
        delayMinutesML: 27,
        varianceVsTraditional: 19,
        platform: '7',
        haltMinutes: 2,
        status: 'SCHEDULED',
      },
      {
        code: 'MMCT',
        name: 'Mumbai Central',
        hindiName: 'मुंबई सेंट्रल',
        distanceKm: 1384,
        scheduledArrival: '08:35',
        scheduledDeparture: '08:35',
        traditionalEta: '08:43',
        dynamicML_Eta: '09:01',
        confidenceIntervalMin: '08:52',
        confidenceIntervalMax: '09:10',
        delayMinutesTraditional: 8,
        delayMinutesML: 26,
        varianceVsTraditional: 18,
        platform: '1',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'Suburban Peak Commuter Corridors (Virar-Borivali-MMCT)',
        impactMinutes: 12,
        description: 'Suburban local train headway prioritization into Mumbai terminal',
        recoverable: false,
      },
    ],
    downstreamCongestionIndex: 64,
    lastUpdatedIso: new Date().toISOString(),
  },

  // 4. 12004 - Lucknow Swarna Shatabdi Express (New Delhi to Lucknow)
  {
    trainNumber: '12004',
    trainName: 'Lucknow Swarna Shatabdi Express',
    hindiName: 'लखनऊ स्वर्ण शताब्दी',
    type: 'SHATABDI',
    zone: 'NR',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'LJN', name: 'Lucknow Junction' },
    totalDistanceKm: 512,
    currentKm: 210,
    lastPassedStation: 'ALJN',
    nextStation: 'TDL',
    currentDelayMinutes: 11,
    traditionalForecastFinalDelayMinutes: 8,
    dynamicMLForecastFinalDelayMinutes: 16,
    confidenceScore: 96,
    locomotive: {
      locoNumber: 'WAP-7 #30288 Ghaziabad',
      locoClass: 'WAP-7 High Speed',
      currentSpeedKmph: 130,
      mpsKmph: 135,
      throttlePercent: 88,
      brakingState: 'RUNNING',
      kavachActive: true,
      currentKm: 210,
      latitude: 27.521,
      longitude: 78.11,
      heading: 'East',
    },
    weather: {
      condition: 'CLEAR',
      visibilityMeters: 4000,
      speedReductionFactor: 1.0,
      fogDeviceActive: false,
      temperatureC: 27,
    },
    currentBlockSection: {
      id: 'SEC-NCR-ALJN-TDL-01',
      sectionName: 'Aligarh - Tundla Main Line',
      startKm: 180,
      endKm: 250,
      signalAspect: 'GREEN',
      trackOccupancyPercent: 44,
      headwayDistanceKm: 11.2,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 130,
      currentBottleneckRating: 'NORMAL',
    },
    speedRestrictions: [],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '06:10',
        scheduledDeparture: '06:10',
        traditionalEta: '06:10',
        dynamicML_Eta: '06:10',
        confidenceIntervalMin: '06:10',
        confidenceIntervalMax: '06:10',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '10',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '06:10',
        actualDeparture: '06:12',
      },
      {
        code: 'GZB',
        name: 'Ghaziabad Junction',
        hindiName: 'गाजियाबाद जंक्शन',
        distanceKm: 25,
        scheduledArrival: '06:48',
        scheduledDeparture: '06:50',
        traditionalEta: '06:50',
        dynamicML_Eta: '06:50',
        confidenceIntervalMin: '06:48',
        confidenceIntervalMax: '06:52',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '2',
        haltMinutes: 2,
        status: 'DEPARTED',
        actualArrival: '06:49',
        actualDeparture: '06:51',
      },
      {
        code: 'ALJN',
        name: 'Aligarh Junction',
        hindiName: 'अलीगढ़ जंक्शन',
        distanceKm: 131,
        scheduledArrival: '07:50',
        scheduledDeparture: '07:52',
        traditionalEta: '08:01',
        dynamicML_Eta: '08:01',
        confidenceIntervalMin: '07:58',
        confidenceIntervalMax: '08:03',
        delayMinutesTraditional: 9,
        delayMinutesML: 9,
        varianceVsTraditional: 0,
        platform: '3',
        haltMinutes: 2,
        status: 'DEPARTED',
        actualArrival: '08:01',
        actualDeparture: '08:03',
      },
      {
        code: 'TDL',
        name: 'Tundla Junction',
        hindiName: 'टूंडला जंक्शन',
        distanceKm: 209,
        scheduledArrival: '08:49',
        scheduledDeparture: '08:51',
        traditionalEta: '09:00',
        dynamicML_Eta: '09:03',
        confidenceIntervalMin: '09:00',
        confidenceIntervalMax: '09:06',
        delayMinutesTraditional: 11,
        delayMinutesML: 12,
        varianceVsTraditional: 1,
        platform: '4',
        haltMinutes: 2,
        status: 'APPROACHING',
      },
      {
        code: 'ETW',
        name: 'Etawah Junction',
        hindiName: 'इटावा जंक्शन',
        distanceKm: 301,
        scheduledArrival: '09:40',
        scheduledDeparture: '09:42',
        traditionalEta: '09:50',
        dynamicML_Eta: '09:55',
        confidenceIntervalMin: '09:51',
        confidenceIntervalMax: '09:59',
        delayMinutesTraditional: 10,
        delayMinutesML: 13,
        varianceVsTraditional: 3,
        platform: '3',
        haltMinutes: 2,
        status: 'SCHEDULED',
      },
      {
        code: 'CNB',
        name: 'Kanpur Central',
        hindiName: 'कानपुर सेंट्रल',
        distanceKm: 440,
        scheduledArrival: '11:20',
        scheduledDeparture: '11:25',
        traditionalEta: '11:30',
        dynamicML_Eta: '11:39',
        confidenceIntervalMin: '11:35',
        confidenceIntervalMax: '11:43',
        delayMinutesTraditional: 10,
        delayMinutesML: 14,
        varianceVsTraditional: 4,
        platform: '5',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'LJN',
        name: 'Lucknow Junction',
        hindiName: 'लखनऊ जंक्शन',
        distanceKm: 512,
        scheduledArrival: '12:40',
        scheduledDeparture: '12:40',
        traditionalEta: '12:48',
        dynamicML_Eta: '12:56',
        confidenceIntervalMin: '12:51',
        confidenceIntervalMax: '13:02',
        delayMinutesTraditional: 8,
        delayMinutesML: 16,
        varianceVsTraditional: 8,
        platform: '6',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'Kanpur Yard Pre-Entrance Squeeze',
        impactMinutes: 6,
        description: 'Terminal junction crossovers and diamond crossings speed drop',
        recoverable: false,
      },
    ],
    downstreamCongestionIndex: 45,
    lastUpdatedIso: new Date().toISOString(),
  },

  // 5. 12802 - Purushottam Express (New Delhi to Puri)
  {
    trainNumber: '12802',
    trainName: 'Purushottam Express',
    hindiName: 'पुरुषोत्तम एक्सप्रेस',
    type: 'SUPERFAST',
    zone: 'ECoR',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'PURI', name: 'Puri' },
    totalDistanceKm: 1865,
    currentKm: 280,
    lastPassedStation: 'ALJN',
    nextStation: 'CNB',
    currentDelayMinutes: 45,
    traditionalForecastFinalDelayMinutes: 30,
    dynamicMLForecastFinalDelayMinutes: 72,
    confidenceScore: 89,
    locomotive: {
      locoNumber: 'WAP-7 #30211 SRC',
      locoClass: 'WAP-7',
      currentSpeedKmph: 85,
      mpsKmph: 130,
      throttlePercent: 60,
      brakingState: 'RUNNING',
      kavachActive: false,
      currentKm: 280,
      latitude: 27.512,
      longitude: 78.43,
      heading: 'Southeast',
    },
    weather: {
      condition: 'DENSE_FOG',
      visibilityMeters: 180,
      speedReductionFactor: 0.6,
      fogDeviceActive: true,
      temperatureC: 14,
    },
    currentBlockSection: {
      id: 'SEC-NCR-TDL-SKB-01',
      sectionName: 'Tundla - Shikohabad Fog Corridor',
      startKm: 230,
      endKm: 310,
      signalAspect: 'YELLOW',
      trackOccupancyPercent: 82,
      headwayDistanceKm: 3.8,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 130,
      currentBottleneckRating: 'SEVERE',
    },
    speedRestrictions: [
      {
        id: 'TSR-FOG-GEN',
        fromKm: 200,
        toKm: 440,
        imposedSpeedKmph: 60,
        normalSpeedKmph: 130,
        cause: 'FOG_SPEED_CAP',
        active: true,
        lengthKm: 240,
        delayImpactMinutes: 34.0,
      },
    ],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '22:40',
        scheduledDeparture: '22:40',
        traditionalEta: '22:40',
        dynamicML_Eta: '22:40',
        confidenceIntervalMin: '22:40',
        confidenceIntervalMax: '22:40',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '8',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '22:40',
        actualDeparture: '22:45',
      },
      {
        code: 'CNB',
        name: 'Kanpur Central',
        hindiName: 'कानपुर सेंट्रल',
        distanceKm: 440,
        scheduledArrival: '04:00',
        scheduledDeparture: '04:05',
        traditionalEta: '04:45',
        dynamicML_Eta: '05:18',
        confidenceIntervalMin: '05:12',
        confidenceIntervalMax: '05:24',
        delayMinutesTraditional: 45,
        delayMinutesML: 78,
        varianceVsTraditional: 33,
        platform: '4',
        haltMinutes: 5,
        status: 'APPROACHING',
      },
      {
        code: 'PRYJ',
        name: 'Prayagraj Junction',
        hindiName: 'प्रयागराज जंक्शन',
        distanceKm: 635,
        scheduledArrival: '06:55',
        scheduledDeparture: '07:00',
        traditionalEta: '07:35',
        dynamicML_Eta: '08:12',
        confidenceIntervalMin: '08:02',
        confidenceIntervalMax: '08:22',
        delayMinutesTraditional: 40,
        delayMinutesML: 77,
        varianceVsTraditional: 37,
        platform: '5',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'DDU',
        name: 'Pt. Deen Dayal Upadhyaya Jn',
        hindiName: 'पंडित दीन दयाल उपाध्याय जं.',
        distanceKm: 788,
        scheduledArrival: '09:40',
        scheduledDeparture: '09:50',
        traditionalEta: '10:15',
        dynamicML_Eta: '10:55',
        confidenceIntervalMin: '10:42',
        confidenceIntervalMax: '11:08',
        delayMinutesTraditional: 35,
        delayMinutesML: 75,
        varianceVsTraditional: 40,
        platform: '2',
        haltMinutes: 10,
        status: 'SCHEDULED',
      },
      {
        code: 'GAYA',
        name: 'Gaya Junction',
        hindiName: 'गया जंक्शन',
        distanceKm: 993,
        scheduledArrival: '12:30',
        scheduledDeparture: '12:35',
        traditionalEta: '13:02',
        dynamicML_Eta: '13:42',
        confidenceIntervalMin: '13:28',
        confidenceIntervalMax: '13:56',
        delayMinutesTraditional: 32,
        delayMinutesML: 72,
        varianceVsTraditional: 40,
        platform: '1',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'BBS',
        name: 'Bhubaneswar',
        hindiName: 'भुवनेश्वर',
        distanceKm: 1802,
        scheduledArrival: '04:15',
        scheduledDeparture: '04:20',
        traditionalEta: '04:45',
        dynamicML_Eta: '05:27',
        confidenceIntervalMin: '05:10',
        confidenceIntervalMax: '05:44',
        delayMinutesTraditional: 30,
        delayMinutesML: 72,
        varianceVsTraditional: 42,
        platform: '2',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'PURI',
        name: 'Puri',
        hindiName: 'पुरी',
        distanceKm: 1865,
        scheduledArrival: '06:15',
        scheduledDeparture: '06:15',
        traditionalEta: '06:45',
        dynamicML_Eta: '07:27',
        confidenceIntervalMin: '07:08',
        confidenceIntervalMax: '07:46',
        delayMinutesTraditional: 30,
        delayMinutesML: 72,
        varianceVsTraditional: 42,
        platform: '4',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'Severe Winter Fog Safety Restriction (NCR Zone)',
        impactMinutes: 34,
        description: 'Speed capped at 60-75 km/h for 240 km between Aligarh and Kanpur',
        recoverable: false,
      },
    ],
    downstreamCongestionIndex: 82,
    lastUpdatedIso: new Date().toISOString(),
  },

  // 6. 12626 - Kerala Express (New Delhi to Thiruvananthapuram Central)
  {
    trainNumber: '12626',
    trainName: 'Kerala Express',
    hindiName: 'केरल एक्सप्रेस',
    type: 'SUPERFAST',
    zone: 'SR',
    origin: { code: 'NDLS', name: 'New Delhi' },
    destination: { code: 'TVC', name: 'Thiruvananthapuram Central' },
    totalDistanceKm: 3026,
    currentKm: 920,
    lastPassedStation: 'BPL',
    nextStation: 'NGP',
    currentDelayMinutes: 52,
    traditionalForecastFinalDelayMinutes: 35,
    dynamicMLForecastFinalDelayMinutes: 88,
    confidenceScore: 91,
    locomotive: {
      locoNumber: 'WAP-7 #30489 Royapuram Shed',
      locoClass: 'WAP-7 High Horsepower',
      currentSpeedKmph: 110,
      mpsKmph: 130,
      throttlePercent: 72,
      brakingState: 'RUNNING',
      kavachActive: true,
      currentKm: 920,
      latitude: 22.18,
      longitude: 78.45,
      heading: 'South',
    },
    weather: {
      condition: 'CLEAR',
      visibilityMeters: 4000,
      speedReductionFactor: 1.0,
      fogDeviceActive: false,
      temperatureC: 30,
    },
    currentBlockSection: {
      id: 'SEC-CR-BPL-NGP-02',
      sectionName: 'Itarsi - Amla Ghat Section',
      startKm: 850,
      endKm: 960,
      signalAspect: 'DOUBLE_YELLOW',
      trackOccupancyPercent: 88,
      headwayDistanceKm: 3.4,
      tractionType: '25kV_AC_ELECTRIC',
      mpsKmph: 110,
      currentBottleneckRating: 'SEVERE',
    },
    speedRestrictions: [
      {
        id: 'TSR-CR-894',
        fromKm: 894,
        toKm: 902,
        imposedSpeedKmph: 20,
        normalSpeedKmph: 110,
        cause: 'TRACK_MAINTENANCE',
        active: true,
        lengthKm: 8,
        delayImpactMinutes: 18.0,
      },
    ],
    stations: [
      {
        code: 'NDLS',
        name: 'New Delhi',
        hindiName: 'नई दिल्ली',
        distanceKm: 0,
        scheduledArrival: '20:10',
        scheduledDeparture: '20:10',
        traditionalEta: '20:10',
        dynamicML_Eta: '20:10',
        confidenceIntervalMin: '20:10',
        confidenceIntervalMax: '20:10',
        delayMinutesTraditional: 0,
        delayMinutesML: 0,
        varianceVsTraditional: 0,
        platform: '5',
        haltMinutes: 0,
        status: 'DEPARTED',
        actualArrival: '20:10',
        actualDeparture: '20:15',
      },
      {
        code: 'BPL',
        name: 'Bhopal Junction',
        hindiName: 'भोपाल जंक्शन',
        distanceKm: 702,
        scheduledArrival: '05:30',
        scheduledDeparture: '05:35',
        traditionalEta: '06:22',
        dynamicML_Eta: '06:22',
        confidenceIntervalMin: '06:20',
        confidenceIntervalMax: '06:24',
        delayMinutesTraditional: 52,
        delayMinutesML: 52,
        varianceVsTraditional: 0,
        platform: '1',
        haltMinutes: 5,
        status: 'DEPARTED',
        actualArrival: '06:22',
        actualDeparture: '06:30',
      },
      {
        code: 'NGP',
        name: 'Nagpur Junction',
        hindiName: 'नागपुर जंक्शन',
        distanceKm: 1090,
        scheduledArrival: '11:55',
        scheduledDeparture: '12:00',
        traditionalEta: '12:43',
        dynamicML_Eta: '13:16',
        confidenceIntervalMin: '13:08',
        confidenceIntervalMax: '13:24',
        delayMinutesTraditional: 48,
        delayMinutesML: 81,
        varianceVsTraditional: 33,
        platform: '2',
        haltMinutes: 5,
        status: 'APPROACHING',
      },
      {
        code: 'BPQ',
        name: 'Balharshah Junction',
        hindiName: 'बल्लारशाह जंक्शन',
        distanceKm: 1298,
        scheduledArrival: '15:20',
        scheduledDeparture: '15:25',
        traditionalEta: '16:04',
        dynamicML_Eta: '16:48',
        confidenceIntervalMin: '16:38',
        confidenceIntervalMax: '16:58',
        delayMinutesTraditional: 44,
        delayMinutesML: 88,
        varianceVsTraditional: 44,
        platform: '3',
        haltMinutes: 5,
        status: 'SCHEDULED',
      },
      {
        code: 'BZA',
        name: 'Vijayawada Junction',
        hindiName: 'विजयवाड़ा जंक्शन',
        distanceKm: 1748,
        scheduledArrival: '21:50',
        scheduledDeparture: '22:00',
        traditionalEta: '22:28',
        dynamicML_Eta: '23:18',
        confidenceIntervalMin: '23:02',
        confidenceIntervalMax: '23:34',
        delayMinutesTraditional: 38,
        delayMinutesML: 88,
        varianceVsTraditional: 50,
        platform: '1',
        haltMinutes: 10,
        status: 'SCHEDULED',
      },
      {
        code: 'CBE',
        name: 'Coimbatore Junction',
        hindiName: 'कोयम्बटूर जंक्शन',
        distanceKm: 2515,
        scheduledArrival: '09:27',
        scheduledDeparture: '09:30',
        traditionalEta: '10:02',
        dynamicML_Eta: '10:55',
        confidenceIntervalMin: '10:35',
        confidenceIntervalMax: '11:15',
        delayMinutesTraditional: 35,
        delayMinutesML: 88,
        varianceVsTraditional: 53,
        platform: '2',
        haltMinutes: 3,
        status: 'SCHEDULED',
      },
      {
        code: 'TVC',
        name: 'Thiruvananthapuram Central',
        hindiName: 'तिरुवनंतपुरम सेंट्रल',
        distanceKm: 3026,
        scheduledArrival: '18:05',
        scheduledDeparture: '18:05',
        traditionalEta: '18:40',
        dynamicML_Eta: '19:33',
        confidenceIntervalMin: '19:10',
        confidenceIntervalMax: '19:56',
        delayMinutesTraditional: 35,
        delayMinutesML: 88,
        varianceVsTraditional: 53,
        platform: '1',
        haltMinutes: 0,
        status: 'SCHEDULED',
      },
    ],
    delayFactors: [
      {
        factor: 'Ghat Section Preceding Train Cascading Halt',
        impactMinutes: 24,
        description: 'Delayed freight rake ahead on single clear aspect block',
        recoverable: false,
      },
    ],
    downstreamCongestionIndex: 88,
    lastUpdatedIso: new Date().toISOString(),
  },
];
